[site]
title = "Kaiji Zhang"
description = "Kaiji's Website"
last_updated = "Jan 18, 2026"

[author]
name = "Kaiji Zhang"
title = "PhD Student"
institution = "University of California, Los Angeles"
avatar = "/kaiji.jpeg"

[social]
# Contact information (leave blank or delete to hide)

email = "kaijizhang@ucla.edu"
google_scholar = "https://scholar.google.com/citations?user=7sY1zR8AAAAJ&hl=en"
linkedin = "www.linkedin.com/in/kaiji-zhang-a6504327a"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"





[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"
