type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "UCLA ECE 121B: Principles of Semiconductor Device Design"
subtitle = "Teaching Assistant"
date = "2026"

tags = ["Undergraduate", "ECE"]

[[items]]
title = "UCLA ECE 101A: Engineering Electromagnetics"
subtitle = "Teaching Assistant"
date = "2025"

tags = ["Undergraduate", "ECE"]

[[items]]
title = "UCLA CHEM 30CL: Organic Chemistry Laboratory II"
subtitle = "Teaching Assistant"
date = "2022"

tags = ["Undergraduate", "CHEM"]
