type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "UCLA ECE 113: Digital Signal Processing"
subtitle = "Teaching Assistant"
date = "2024"

tags = ["Undergraduate", "ECE"]

[[items]]
title = "UCLA ECE 131A: Probability and Statistics"
subtitle = "Teaching Assistant"
date = "2025"

tags = ["Undergraduate", "ECE"]

[[items]]
title = "UCLA ECE 114: Imaging and Audio Processing"
subtitle = "Teaching Assistant"
date = "2025"

tags = ["Undergraduate", "ECE"]
